In [1]:

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [2]:
# Importing the dataset
dataset = pd.read_csv('HR-Employee-Attrition.csv')
columns = [0,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,27,28,29,30,31,32,33,34]
X = dataset.iloc[:,columns].values
y = dataset.iloc[:, 1].values



In [3]:
dataset.shape

(1470, 35)

In [4]:
X[2]

array([37, 1373, 'Research & Development', 2, 2, 1, 4, 4, 'Male', 92, 2,
       1, 'Laboratory Technician', 3, 'Single', 2090, 2396, 6, 'Yes', 15,
       3, 2, 0, 7, 3, 3, 0, 0, 0, 0], dtype=object)

In [5]:
X.shape

(1470, 30)

In [6]:
y

array(['Yes', 'No', 'Yes', ..., 'No', 'No', 'No'], dtype=object)

In [7]:
#Econding categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,2] = labelencoder_X_1.fit_transform(X[:,2])
labelencoder_X_2 = LabelEncoder()
X[:,8] = labelencoder_X_2.fit_transform(X[:,8])
labelencoder_X_3 = LabelEncoder()
X[:,12] = labelencoder_X_3.fit_transform(X[:,12])
labelencoder_X_4 = LabelEncoder()
X[:,14] = labelencoder_X_4.fit_transform(X[:,14])
labelencoder_X_5 = LabelEncoder()
X[:,18] = labelencoder_X_5.fit_transform(X[:,18])
onehotencoder = OneHotEncoder(categorical_features = [2])
X = onehotencoder.fit_transform(X).toarray()
# X = X[:,:]


D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [8]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [9]:
y

array([1, 0, 1, ..., 0, 0, 0])

In [10]:
X[2]

array([0.000e+00, 1.000e+00, 0.000e+00, 3.700e+01, 1.373e+03, 2.000e+00,
       2.000e+00, 1.000e+00, 4.000e+00, 4.000e+00, 1.000e+00, 9.200e+01,
       2.000e+00, 1.000e+00, 2.000e+00, 3.000e+00, 2.000e+00, 2.090e+03,
       2.396e+03, 6.000e+00, 1.000e+00, 1.500e+01, 3.000e+00, 2.000e+00,
       0.000e+00, 7.000e+00, 3.000e+00, 3.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00])

In [11]:
X.shape

(1470, 32)

In [12]:
y.shape

(1470,)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=0)


In [14]:
X_train.shape

(1176, 32)

In [15]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [16]:
X_train.shape

(1176, 32)

In [17]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [18]:
classifier = Sequential()
classifier.add(Dense(output_dim=23,init='uniform',activation='relu',input_dim=32))
classifier.add(Dense(output_dim=12,init='uniform',activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=32, units=23, kernel_initializer="uniform")`
  
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [19]:
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [20]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [21]:
classifier.fit(X_train,y_train,epochs=10)

Instructions for updating:
Use tf.cast instead.
Epoch 1/10
1176/1176 [==============================] - 0s 406us/step - loss: 0.6856 - acc: 0.8257
Epoch 2/10
1176/1176 [==============================] - 0s 33us/step - loss: 0.6452 - acc: 0.8401
Epoch 3/10
1176/1176 [==============================] - 0s 33us/step - loss: 0.4993 - acc: 0.8401
Epoch 4/10
1176/1176 [==============================] - 0s 31us/step - loss: 0.3945 - acc: 0.8401
Epoch 5/10
1176/1176 [==============================] - 0s 29us/step - loss: 0.3709 - acc: 0.8401
Epoch 6/10
1176/1176 [==============================] - 0s 31us/step - loss: 0.3601 - acc: 0.8401
Epoch 7/10
1176/1176 [==============================] - 0s 31us/step - loss: 0.3517 - acc: 0.8401
Epoch 8/10
1176/1176 [==============================] - 0s 31us/step - loss: 0.3454 - acc: 0.8401
Epoch 9/10
1176/1176 [==============================] - 0s 29us/step - loss: 0.3389 - acc: 0.8401
Epoch 10/10
1176/1176 [==============================] - 0s 28us/step

In [22]:
loss, acc = classifier.evaluate(X_test,y_test)

294/294 [==============================] - 0s 220us/step


In [23]:
acc = acc*100

In [24]:
loss,acc

(0.34939738905348744, 83.33333329278597)