In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
train_data.shape

(1460, 81)

In [5]:
train_data = train_data.drop(['Alley'],axis = 1)
train_data = train_data.drop(['PoolQC'],axis = 1)
train_data = train_data.drop(['Fence'],axis = 1)
train_data = train_data.drop(['MiscFeature'],axis = 1)
train_data = train_data.drop(['FireplaceQu'],axis = 1)
train_data = train_data.fillna({"LotFrontage": round(np.mean(train_data['LotFrontage']))})
train_data = train_data.fillna({"MasVnrType": "RL"})
train_data = train_data.fillna({"MasVnrArea": round(np.mean(train_data['MasVnrArea']))})
train_data = train_data.fillna({"BsmtQual": "TA"})
train_data = train_data.fillna({"BsmtCond": "TA"})
train_data = train_data.fillna({"BsmtExposure": "No"})
train_data = train_data.fillna({"BsmtFinType1": "Unf"})
train_data = train_data.fillna({"BsmtFinType2": "Unf"})
train_data = train_data.fillna({"Electrical": "SBrkr"})
train_data = train_data.fillna({"GarageType": "Attchd"})
train_data = train_data.fillna({"GarageYrBlt": round(np.mean(train_data['GarageYrBlt']))})
train_data = train_data.fillna({"GarageFinish": "Unf"})
train_data = train_data.fillna({"GarageQual": "TA"})
train_data = train_data.fillna({"GarageCond": "TA"})

In [6]:
X = train_data.iloc[:,0:-1].values
y = train_data.iloc[:,-1].values

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,2] = labelencoder_X.fit_transform(X[:,2])
labelencoder_X_2 = LabelEncoder()
X[:,5] = labelencoder_X_2.fit_transform(X[:,5])
labelencoder_X_3 = LabelEncoder()
X[:,6] = labelencoder_X_3.fit_transform(X[:,6])
labelencoder_X_4 = LabelEncoder()
X[:,7] = labelencoder_X_4.fit_transform(X[:,7])
labelencoder_X_5 = LabelEncoder()
X[:,8] = labelencoder_X_5.fit_transform(X[:,8])
labelencoder_X_6 = LabelEncoder()
X[:,9] = labelencoder_X_6.fit_transform(X[:,9])
labelencoder_X_7 = LabelEncoder()
X[:,10] = labelencoder_X_7.fit_transform(X[:,10])
labelencoder_X_8 = LabelEncoder()
X[:,11] = labelencoder_X_8.fit_transform(X[:,11])
labelencoder_X_9 = LabelEncoder()
X[:,12] = labelencoder_X_9.fit_transform(X[:,12])
labelencoder_X_10 = LabelEncoder()
X[:,13] = labelencoder_X_10.fit_transform(X[:,13])
labelencoder_X_11 = LabelEncoder()
X[:,14] = labelencoder_X_11.fit_transform(X[:,14])
labelencoder_X_12 = LabelEncoder()
X[:,15] = labelencoder_X_12.fit_transform(X[:,15])
labelencoder_X_13 = LabelEncoder()
X[:,20] = labelencoder_X_13.fit_transform(X[:,20])
labelencoder_X_14 = LabelEncoder()
X[:,21] = labelencoder_X_14.fit_transform(X[:,21])
labelencoder_X_15 = LabelEncoder()
X[:,22] = labelencoder_X_15.fit_transform(X[:,22])
labelencoder_X_16 = LabelEncoder()
X[:,23] = labelencoder_X_16.fit_transform(X[:,23])
labelencoder_X_17 = LabelEncoder()
X[:,24] = labelencoder_X_17.fit_transform(X[:,24])
labelencoder_X_18 = LabelEncoder()
X[:,26] = labelencoder_X_18.fit_transform(X[:,26])
labelencoder_X_19 = LabelEncoder()
X[:,27] = labelencoder_X_19.fit_transform(X[:,27])
labelencoder_X_20 = LabelEncoder()
X[:,28] = labelencoder_X_20.fit_transform(X[:,28])
labelencoder_X_21 = LabelEncoder()
X[:,29] = labelencoder_X_21.fit_transform(X[:,29])
labelencoder_X_22 = LabelEncoder()
X[:,30] = labelencoder_X_22.fit_transform(X[:,30])
labelencoder_X_23 = LabelEncoder()
X[:,31] = labelencoder_X_23.fit_transform(X[:,31])
labelencoder_X_24 = LabelEncoder()
X[:,32] = labelencoder_X_24.fit_transform(X[:,32])
labelencoder_X_25 = LabelEncoder()
X[:,34] = labelencoder_X_25.fit_transform(X[:,34])
labelencoder_X_26 = LabelEncoder()
X[:,38] = labelencoder_X_26.fit_transform(X[:,38])
labelencoder_X_27 = LabelEncoder()
X[:,39] = labelencoder_X_27.fit_transform(X[:,39])
labelencoder_X_28 = LabelEncoder()
X[:,40] = labelencoder_X_28.fit_transform(X[:,40])
labelencoder_X_29 = LabelEncoder()
X[:,41] = labelencoder_X_29.fit_transform(X[:,41])
labelencoder_X_30 = LabelEncoder()
X[:,52] = labelencoder_X_30.fit_transform(X[:,52])
labelencoder_X_31 = LabelEncoder()
X[:,54] = labelencoder_X_31.fit_transform(X[:,54])
labelencoder_X_32 = LabelEncoder()
X[:,56] = labelencoder_X_32.fit_transform(X[:,56])
labelencoder_X_33 = LabelEncoder()
X[:,58] = labelencoder_X_33.fit_transform(X[:,58])
labelencoder_X_34 = LabelEncoder()
X[:,61] = labelencoder_X_34.fit_transform(X[:,61])
labelencoder_X_35 = LabelEncoder()
X[:,62] = labelencoder_X_35.fit_transform(X[:,62])
labelencoder_X_36 = LabelEncoder()
X[:,63] = labelencoder_X_36.fit_transform(X[:,63])
labelencoder_X_37 = LabelEncoder()
X[:,73] = labelencoder_X_37.fit_transform(X[:,73])
labelencoder_X_38 = LabelEncoder()
X[:,74] = labelencoder_X_38.fit_transform(X[:,74])

In [8]:
X

array([[1, 60, 3, ..., 2008, 8, 4],
       [2, 20, 3, ..., 2007, 8, 4],
       [3, 60, 3, ..., 2008, 8, 4],
       ...,
       [1458, 70, 3, ..., 2010, 8, 4],
       [1459, 20, 3, ..., 2010, 8, 4],
       [1460, 20, 3, ..., 2008, 8, 4]], dtype=object)

In [9]:
X[0]

array([1, 60, 3, 65.0, 8450, 1, 3, 3, 0, 4, 0, 5, 2, 2, 0, 5, 7, 5, 2003,
       2003, 1, 1, 12, 13, 1, 196.0, 2, 4, 2, 2, 3, 3, 2, 706, 5, 0, 150,
       856, 1, 0, 1, 4, 856, 854, 0, 1710, 1, 0, 2, 1, 3, 1, 2, 8, 6, 0,
       1, 2003.0, 1, 2, 548, 4, 4, 2, 0, 61, 0, 0, 0, 0, 0, 2, 2008, 8, 4],
      dtype=object)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X.shape

(1460, 75)

In [12]:
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [13]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.05)

In [14]:
x_train.shape

(1387, 75)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [17]:
y_pred = reg.predict(x_test)

In [18]:
from sklearn.metrics import mean_squared_error

In [19]:
mean_squared_error(y_test, y_pred)

575243493.4116373

In [20]:
test_data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [21]:
test_data = test_data.drop(['Alley'],axis = 1)
test_data = test_data.drop(['PoolQC'],axis = 1)
test_data = test_data.drop(['Fence'],axis = 1)
test_data = test_data.drop(['MiscFeature'],axis = 1)
test_data = test_data.drop(['FireplaceQu'],axis = 1)
test_data = test_data.fillna({"LotFrontage": round(np.mean(test_data['LotFrontage']))})
test_data = test_data.fillna({"MSZoning": "RL"})
test_data = test_data.fillna({"Utilities": "AllPub"})
test_data = test_data.fillna({"Exterior1st": "VinylSd"})
test_data = test_data.fillna({"Exterior2nd": "VinylSd"})
test_data = test_data.fillna({"MasVnrType": "RL"})
test_data = test_data.fillna({"MasVnrArea": round(np.mean(test_data['MasVnrArea']))})
test_data = test_data.fillna({"BsmtQual": "TA"})
test_data = test_data.fillna({"BsmtCond": "TA"})
test_data = test_data.fillna({"BsmtExposure": "No"})
test_data = test_data.fillna({"BsmtFinType1": "GLQ"})
test_data = test_data.fillna({"BsmtFinType2": "Unf"})
test_data = test_data.fillna({"BsmtFinSF1": round(np.mean(test_data['BsmtFinSF1']))})
test_data = test_data.fillna({"BsmtFinSF2": round(np.mean(test_data['BsmtFinSF2']))})
test_data = test_data.fillna({"BsmtUnfSF": round(np.mean(test_data['BsmtUnfSF']))})
test_data = test_data.fillna({"TotalBsmtSF": round(np.mean(test_data['TotalBsmtSF']))})
test_data = test_data.fillna({"BsmtFullBath": round(np.mean(test_data['BsmtFullBath']))})
test_data = test_data.fillna({"BsmtHalfBath": round(np.mean(test_data['BsmtHalfBath']))})
test_data = test_data.fillna({"KitchenQual": "TA"})
test_data = test_data.fillna({"Functional": "Typ"})
test_data = test_data.fillna({"GarageType": "Attchd"})
test_data = test_data.fillna({"GarageYrBlt": round(np.mean(test_data['GarageYrBlt']))})
test_data = test_data.fillna({"GarageFinish": "Unf"})
test_data = test_data.fillna({"GarageCars": round(np.mean(test_data['GarageCars']))})
test_data = test_data.fillna({"GarageArea": round(np.mean(test_data['GarageArea']))})
test_data = test_data.fillna({"GarageQual": "TA"})
test_data = test_data.fillna({"GarageCond": "TA"})
test_data = test_data.fillna({"SaleType": "WD"})

In [22]:
X2 = test_data.iloc[:,:].values

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X2[:,2] = labelencoder_X.fit_transform(X2[:,2])
labelencoder_X_2 = LabelEncoder()
X2[:,5] = labelencoder_X_2.fit_transform(X2[:,5])
labelencoder_X_3 = LabelEncoder()
X2[:,6] = labelencoder_X_3.fit_transform(X2[:,6])
labelencoder_X_4 = LabelEncoder()
X2[:,7] = labelencoder_X_4.fit_transform(X2[:,7])
labelencoder_X_5 = LabelEncoder()
X2[:,8] = labelencoder_X_5.fit_transform(X2[:,8])
labelencoder_X_6 = LabelEncoder()
X2[:,9] = labelencoder_X_6.fit_transform(X2[:,9])
labelencoder_X_7 = LabelEncoder()
X2[:,10] = labelencoder_X_7.fit_transform(X2[:,10])
labelencoder_X_8 = LabelEncoder()
X2[:,11] = labelencoder_X_8.fit_transform(X2[:,11])
labelencoder_X_9 = LabelEncoder()
X2[:,12] = labelencoder_X_9.fit_transform(X2[:,12])
labelencoder_X_10 = LabelEncoder()
X2[:,13] = labelencoder_X_10.fit_transform(X2[:,13])
labelencoder_X_11 = LabelEncoder()
X2[:,14] = labelencoder_X_11.fit_transform(X2[:,14])
labelencoder_X_12 = LabelEncoder()
X2[:,15] = labelencoder_X_12.fit_transform(X2[:,15])
labelencoder_X_13 = LabelEncoder()
X2[:,20] = labelencoder_X_13.fit_transform(X2[:,20])
labelencoder_X_14 = LabelEncoder()
X2[:,21] = labelencoder_X_14.fit_transform(X2[:,21])
labelencoder_X_15 = LabelEncoder()
X2[:,22] = labelencoder_X_15.fit_transform(X2[:,22])
labelencoder_X_16 = LabelEncoder()
X2[:,23] = labelencoder_X_16.fit_transform(X2[:,23])
labelencoder_X_17 = LabelEncoder()
X2[:,24] = labelencoder_X_17.fit_transform(X2[:,24])
labelencoder_X_18 = LabelEncoder()
X2[:,26] = labelencoder_X_18.fit_transform(X2[:,26])
labelencoder_X_19 = LabelEncoder()
X2[:,27] = labelencoder_X_19.fit_transform(X2[:,27])
labelencoder_X_20 = LabelEncoder()
X2[:,28] = labelencoder_X_20.fit_transform(X2[:,28])
labelencoder_X_21 = LabelEncoder()
X2[:,29] = labelencoder_X_21.fit_transform(X2[:,29])
labelencoder_X_22 = LabelEncoder()
X2[:,30] = labelencoder_X_22.fit_transform(X2[:,30])
labelencoder_X_23 = LabelEncoder()
X2[:,31] = labelencoder_X_23.fit_transform(X2[:,31])
labelencoder_X_24 = LabelEncoder()
X2[:,32] = labelencoder_X_24.fit_transform(X2[:,32])
labelencoder_X_25 = LabelEncoder()
X2[:,34] = labelencoder_X_25.fit_transform(X2[:,34])
labelencoder_X_26 = LabelEncoder()
X2[:,38] = labelencoder_X_26.fit_transform(X2[:,38])
labelencoder_X_27 = LabelEncoder()
X2[:,39] = labelencoder_X_27.fit_transform(X2[:,39])
labelencoder_X_28 = LabelEncoder()
X2[:,40] = labelencoder_X_28.fit_transform(X2[:,40])
labelencoder_X_29 = LabelEncoder()
X2[:,41] = labelencoder_X_29.fit_transform(X2[:,41])
labelencoder_X_30 = LabelEncoder()
X2[:,52] = labelencoder_X_30.fit_transform(X2[:,52])
labelencoder_X_31 = LabelEncoder()
X2[:,54] = labelencoder_X_31.fit_transform(X2[:,54])
labelencoder_X_32 = LabelEncoder()
X2[:,56] = labelencoder_X_32.fit_transform(X2[:,56])
labelencoder_X_33 = LabelEncoder()
X2[:,58] = labelencoder_X_33.fit_transform(X2[:,58])
labelencoder_X_34 = LabelEncoder()
X2[:,61] = labelencoder_X_34.fit_transform(X2[:,61])
labelencoder_X_35 = LabelEncoder()
X2[:,62] = labelencoder_X_35.fit_transform(X2[:,62])
labelencoder_X_36 = LabelEncoder()
X2[:,63] = labelencoder_X_36.fit_transform(X2[:,63])
labelencoder_X_37 = LabelEncoder()
X2[:,73] = labelencoder_X_37.fit_transform(X2[:,73])
labelencoder_X_38 = LabelEncoder()
X2[:,74] = labelencoder_X_38.fit_transform(X2[:,74])

In [24]:
X2

array([[1461, 20, 2, ..., 2010, 8, 4],
       [1462, 20, 3, ..., 2010, 8, 4],
       [1463, 60, 3, ..., 2010, 8, 4],
       ...,
       [2917, 20, 3, ..., 2006, 8, 0],
       [2918, 85, 3, ..., 2006, 8, 4],
       [2919, 60, 3, ..., 2006, 8, 4]], dtype=object)

In [25]:
y_pred2 = reg.predict(X2)

In [26]:
y_pred2.shape

(1459,)

In [27]:
y_pred2

array([105876.86031685, 148193.23881705, 166347.03516145, ...,
       137514.98578235, 110674.57836782, 240424.01747016])

In [28]:
submit = pd.DataFrame()
submit['Id'] = test_data['Id'].values
submit['SalePrice'] = y_pred2.round()

In [29]:
submit.head()

Id  SalePrice
0  1461   105877.0
1  1462   148193.0
2  1463   166347.0
3  1464   181328.0
4  1465   186896.0

In [30]:
submit_file = submit.to_csv('submissionWFS.csv', index = False)