In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [4]:
train.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [5]:
train.describe(include='all')

User_ID Product_ID  Gender     Age     Occupation City_Category  \
count   5.500680e+05     550068  550068  550068  550068.000000        550068   
unique           NaN       3631       2       7            NaN             3   
top              NaN  P00265242       M   26-35            NaN             B   
freq             NaN       1880  414259  219587            NaN        231173   
mean    1.003029e+06        NaN     NaN     NaN       8.076707           NaN   
std     1.727592e+03        NaN     NaN     NaN       6.522660           NaN   
min     1.000001e+06        NaN     NaN     NaN       0.000000           NaN   
25%     1.001516e+06        NaN     NaN     NaN       2.000000           NaN   
50%     1.003077e+06        NaN     NaN     NaN       7.000000           NaN   
75%     1.004478e+06        NaN     NaN     NaN      14.000000           NaN   
max     1.006040e+06        NaN     NaN     NaN      20.000000           NaN   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
count                      550068   550068.000000       550068.000000   
unique                          5             NaN                 NaN   
top                             1             NaN                 NaN   
freq                       193821             NaN                 NaN   
mean                          NaN        0.409653            5.404270   
std                           NaN        0.491770            3.936211   
min                           NaN        0.000000            1.000000   
25%                           NaN        0.000000            1.000000   
50%                           NaN        0.000000            5.000000   
75%                           NaN        1.000000            8.000000   
max                           NaN        1.000000           20.000000   

        Product_Category_2  Product_Category_3       Purchase  
count        376430.000000       166821.000000  550068.000000  
unique                 NaN                 NaN            NaN  
top                    NaN                 NaN            NaN  
freq                   NaN                 NaN            NaN  
mean              9.842329           12.668243    9263.968713  
std               5.086590            4.125338    5023.065394  
min               2.000000            3.000000      12.000000  
25%               5.000000            9.000000    5823.000000  
50%               9.000000           14.000000    8047.000000  
75%              15.000000           16.000000   12054.000000  
max              18.000000           18.000000   23961.000000

In [6]:
train = train.fillna({"Product_Category_2": "9.84"})
train = train.fillna({"Product_Category_3": "12.66"})

In [7]:
train.shape

(550068, 12)

In [8]:
X = train.iloc[:,0:-1].values
y = train.iloc[:,-1].values

In [9]:
X.shape, y.shape

((550068, 11), (550068,))

In [10]:
train.describe(include="O")

Product_ID  Gender     Age City_Category Stay_In_Current_City_Years  \
count      550068  550068  550068        550068                     550068   
unique       3631       2       7             3                          5   
top     P00265242       M   26-35             B                          1   
freq         1880  414259  219587        231173                     193821   

       Product_Category_2 Product_Category_3  
count              550068             550068  
unique                 18                 16  
top                  9.84              12.66  
freq               173638             383247

In [11]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
labelencoder_X_3 = LabelEncoder()
X[:,3] = labelencoder_X_3.fit_transform(X[:,3])
labelencoder_X_4 = LabelEncoder()
X[:,5] = labelencoder_X_4.fit_transform(X[:,5])
labelencoder_X_5 = LabelEncoder()
X[:,6] = labelencoder_X_5.fit_transform(X[:,6])
#labelencoder_X_6 = LabelEncoder()
#X[:,9] = labelencoder_X_6.fit_transform(X[:,9])
#labelencoder_X_7 = LabelEncoder()
#X[:,10] = labelencoder_X_7.fit_transform(X[:,10])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [14]:
X_train.shape

(440054, 11)

In [15]:
from sklearn.ensemble import RandomForestRegressor

In [16]:
reg = RandomForestRegressor(n_estimators= 50, random_state = 0)
reg.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [17]:
y_pred = reg.predict(X_test)

In [18]:
y_pred

array([ 7914.98, 14009.02,  8482.82, ...,  2172.94,  5574.18,  6954.02])

In [19]:
from sklearn.metrics import mean_squared_error

In [20]:
mse = mean_squared_error(y_test, y_pred)

In [21]:
rmse = np.sqrt(mse)

In [22]:
mse, rmse

(7623529.433246633, 2761.073963740673)

In [23]:
test.head()

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000004  P00128942      M  46-50           7             B   
1  1000009  P00113442      M  26-35          17             C   
2  1000010  P00288442      F  36-45           1             B   
3  1000010  P00145342      F  36-45           1             B   
4  1000011  P00053842      F  26-35           1             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               1                   1   
1                          0               0                   3   
2                         4+               1                   5   
3                         4+               1                   4   
4                          1               0                   4   

   Product_Category_2  Product_Category_3  
0                11.0                 NaN  
1                 5.0                 NaN  
2                14.0                 NaN  
3                 9.0                 NaN  
4                 5.0                12.0

In [24]:
test.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2             72344
Product_Category_3            162562
dtype: int64

In [25]:
test.describe(include='all')

User_ID Product_ID  Gender     Age     Occupation City_Category  \
count   2.335990e+05     233599  233599  233599  233599.000000        233599   
unique           NaN       3491       2       7            NaN             3   
top              NaN  P00265242       M   26-35            NaN             B   
freq             NaN        829  175772   93428            NaN         98566   
mean    1.003029e+06        NaN     NaN     NaN       8.085407           NaN   
std     1.726505e+03        NaN     NaN     NaN       6.521146           NaN   
min     1.000001e+06        NaN     NaN     NaN       0.000000           NaN   
25%     1.001527e+06        NaN     NaN     NaN       2.000000           NaN   
50%     1.003070e+06        NaN     NaN     NaN       7.000000           NaN   
75%     1.004477e+06        NaN     NaN     NaN      14.000000           NaN   
max     1.006040e+06        NaN     NaN     NaN      20.000000           NaN   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
count                      233599   233599.000000       233599.000000   
unique                          5             NaN                 NaN   
top                             1             NaN                 NaN   
freq                        82604             NaN                 NaN   
mean                          NaN        0.410070            5.276542   
std                           NaN        0.491847            3.736380   
min                           NaN        0.000000            1.000000   
25%                           NaN        0.000000            1.000000   
50%                           NaN        0.000000            5.000000   
75%                           NaN        1.000000            8.000000   
max                           NaN        1.000000           18.000000   

        Product_Category_2  Product_Category_3  
count        161255.000000        71037.000000  
unique                 NaN                 NaN  
top                    NaN                 NaN  
freq                   NaN                 NaN  
mean              9.849586           12.669454  
std               5.094943            4.125944  
min               2.000000            3.000000  
25%               5.000000            9.000000  
50%               9.000000           14.000000  
75%              15.000000           16.000000  
max              18.000000           18.000000

In [26]:
test = test.fillna({"Product_Category_2": "9.84"})
test = test.fillna({"Product_Category_3": "12.66"})

In [27]:
X2 = test.iloc[:,:].values

In [28]:
test.describe(include="O")

Product_ID  Gender     Age City_Category Stay_In_Current_City_Years  \
count      233599  233599  233599        233599                     233599   
unique       3491       2       7             3                          5   
top     P00265242       M   26-35             B                          1   
freq          829  175772   93428         98566                      82604   

       Product_Category_2 Product_Category_3  
count              233599             233599  
unique                 18                 16  
top                  9.84              12.66  
freq                72344             162562

In [29]:
X2[0]

array([1000004, 'P00128942', 'M', '46-50', 7, 'B', '2', 1, 1, 11.0,
       '12.66'], dtype=object)

In [30]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X2[:,1] = labelencoder_X.fit_transform(X2[:,1])
labelencoder_X_2 = LabelEncoder()
X2[:,2] = labelencoder_X_2.fit_transform(X2[:,2])
labelencoder_X_3 = LabelEncoder()
X2[:,3] = labelencoder_X_3.fit_transform(X2[:,3])
labelencoder_X_4 = LabelEncoder()
X2[:,5] = labelencoder_X_4.fit_transform(X2[:,5])
labelencoder_X_5 = LabelEncoder()
X2[:,6] = labelencoder_X_5.fit_transform(X2[:,6])
#labelencoder_X_6 = LabelEncoder()
#X2[:,9] = labelencoder_X_6.fit_transform(X2[:,9])
#labelencoder_X_7 = LabelEncoder()
#X2[:,10] = labelencoder_X_7.fit_transform(X2[:,10])

In [31]:
X2.shape

(233599, 11)

In [32]:
y_pred2 = reg.predict(X2)

In [33]:
y_pred2

array([11663.96, 10153.6 ,  4242.24, ..., 11164.02, 22007.3 ,  2367.52])

In [34]:
# comb

In [35]:
submit = pd.DataFrame()
submit['User_ID'] = test['User_ID'].values
submit['Product_ID'] = test['Product_ID'].values
submit['Purchase'] = y_pred2.round().astype(int)

In [36]:
submit.head()

User_ID Product_ID  Purchase
0  1000004  P00128942     11664
1  1000009  P00113442     10154
2  1000010  P00288442      4242
3  1000010  P00145342      2245
4  1000011  P00053842      2944

In [37]:
submit_file = submit.to_csv('submissionsimple.csv', index = False)