In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

In [3]:
train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
train_data.describe(include="all")

PassengerId    Survived      Pclass                          Name  \
count    891.000000  891.000000  891.000000                           891   
unique          NaN         NaN         NaN                           891   
top             NaN         NaN         NaN  Theobald, Mr. Thomas Leonard   
freq            NaN         NaN         NaN                             1   
mean     446.000000    0.383838    2.308642                           NaN   
std      257.353842    0.486592    0.836071                           NaN   
min        1.000000    0.000000    1.000000                           NaN   
25%      223.500000    0.000000    2.000000                           NaN   
50%      446.000000    0.000000    3.000000                           NaN   
75%      668.500000    1.000000    3.000000                           NaN   
max      891.000000    1.000000    3.000000                           NaN   

         Sex         Age       SibSp       Parch  Ticket        Fare  \
count    891  714.000000  891.000000  891.000000     891  891.000000   
unique     2         NaN         NaN         NaN     681         NaN   
top     male         NaN         NaN         NaN  347082         NaN   
freq     577         NaN         NaN         NaN       7         NaN   
mean     NaN   29.699118    0.523008    0.381594     NaN   32.204208   
std      NaN   14.526497    1.102743    0.806057     NaN   49.693429   
min      NaN    0.420000    0.000000    0.000000     NaN    0.000000   
25%      NaN   20.125000    0.000000    0.000000     NaN    7.910400   
50%      NaN   28.000000    0.000000    0.000000     NaN   14.454200   
75%      NaN   38.000000    1.000000    0.000000     NaN   31.000000   
max      NaN   80.000000    8.000000    6.000000     NaN  512.329200   

              Cabin Embarked  
count           204      889  
unique          147        3  
top     C23 C25 C27        S  
freq              4      644  
mean            NaN      NaN  
std             NaN      NaN  
min             NaN      NaN  
25%             NaN      NaN  
50%             NaN      NaN  
75%             NaN      NaN  
max             NaN      NaN

In [5]:
train_data = train_data.drop(['Name'],axis = 1)
train_data = train_data.drop(['Cabin'],axis = 1)
train_data = train_data.drop(['Ticket'],axis = 1)

In [6]:
train_data.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [7]:
train_data = train_data.fillna({"Embarked": "S"})
train_data = train_data.fillna({"Age": "30"})

In [8]:
train_data.shape

(891, 9)

In [9]:
X = train_data.iloc[:, 2:9].values
y = train_data.iloc[:, 1]

In [10]:
X[0,6]

'S'

In [11]:
X[0]

array([3, 'male', 22.0, 1, 0, 7.25, 'S'], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,6] = labelencoder_X_2.fit_transform(X[:,6])
onehotencoder = OneHotEncoder(categorical_features=[6])
X = onehotencoder.fit_transform(X).toarray()

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [15]:
#from sklearn.decomposition import PCA
#pca = PCA(n_components=3)
#X_train = pca.fit_transform(X_train)
#X_test = pca.transform(X_test)


In [16]:
#explained_variance = pca.explained_variance_ratio_

In [17]:
#explained_variance

In [18]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state=0)
regressor.fit(X_train,y_train)


D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [19]:
y_pred = regressor.predict(X_test)

In [20]:
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [22]:
cm

array([[96, 14],
       [19, 50]], dtype=int64)

In [23]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf',random_state= 0 )
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [24]:
y_pred2 = classifier.predict(X_test)

In [25]:
y_pred2

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0], dtype=int64)

In [26]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test,y_pred2)

In [27]:
cm2

array([[99, 11],
       [24, 45]], dtype=int64)

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier1 = GaussianNB()
classifier1.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [29]:
y_pred3 = classifier1.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test,y_pred3)

In [31]:
cm3

array([[94, 16],
       [18, 51]], dtype=int64)

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [33]:
y_pred4 = classifier2.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix
cm4 = confusion_matrix(y_test,y_pred4)

In [35]:
cm4

array([[82, 28],
       [21, 48]], dtype=int64)

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators= 10,criterion = 'entropy', random_state = 0)
classifier3.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
y_pred5 = classifier3.predict(X_test)

In [38]:
from sklearn.metrics import confusion_matrix
cm5 = confusion_matrix(y_test,y_pred5)

In [39]:
cm5

array([[104,   6],
       [ 21,  48]], dtype=int64)

# Testing on test_data

In [40]:
def prediction(test_data):
    test_data = test_data.drop(['Name'],axis = 1)
    test_data = test_data.drop(['Cabin'],axis = 1)
    test_data = test_data.drop(['Ticket'],axis = 1)
    test_data = test_data.fillna({"Embarked": "S"})
    test_data = test_data.fillna({"Age": round(np.mean(test_data['Age']))})
    test_data = test_data.fillna({"Fare": round(np.mean(test_data['Fare']), ndigits = 4)})
    test_X = test_data.iloc[:, 1:8].values
    labelencoder_X = LabelEncoder()
    test_X[:,1] = labelencoder_X.fit_transform(test_X[:,1])
    labelencoder_X_2 = LabelEncoder()
    test_X[:,6] = labelencoder_X_2.fit_transform(test_X[:,6])
    onehotencoder = OneHotEncoder(categorical_features=[6])
    test_X = onehotencoder.fit_transform(test_X).toarray()
    test_X = sc.transform(test_X)
    pred = classifier3.predict(test_X)
    return pred

In [41]:
pred = prediction(test_data)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [42]:
submit = pd.DataFrame()
submit['PassengerId'] = test_data['PassengerId'].values
submit['Survived'] = pred

In [43]:
submit.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [44]:
submit_file = submit.to_csv('submission.csv', index = False)