In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
train.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [4]:
train.describe(include='all')

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
count             8523  7060.000000             8523      8523.000000   
unique            1559          NaN                5              NaN   
top              FDW13          NaN          Low Fat              NaN   
freq                10          NaN             5089              NaN   
mean               NaN    12.857645              NaN         0.066132   
std                NaN     4.643456              NaN         0.051598   
min                NaN     4.555000              NaN         0.000000   
25%                NaN     8.773750              NaN         0.026989   
50%                NaN    12.600000              NaN         0.053931   
75%                NaN    16.850000              NaN         0.094585   
max                NaN    21.350000              NaN         0.328391   

                    Item_Type     Item_MRP Outlet_Identifier  \
count                    8523  8523.000000              8523   
unique                     16          NaN                10   
top     Fruits and Vegetables          NaN            OUT027   
freq                     1232          NaN               935   
mean                      NaN   140.992782               NaN   
std                       NaN    62.275067               NaN   
min                       NaN    31.290000               NaN   
25%                       NaN    93.826500               NaN   
50%                       NaN   143.012800               NaN   
75%                       NaN   185.643700               NaN   
max                       NaN   266.888400               NaN   

        Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
count                 8523.000000        6113                 8523   
unique                        NaN           3                    3   
top                           NaN      Medium               Tier 3   
freq                          NaN        2793                 3350   
mean                  1997.831867         NaN                  NaN   
std                      8.371760         NaN                  NaN   
min                   1985.000000         NaN                  NaN   
25%                   1987.000000         NaN                  NaN   
50%                   1999.000000         NaN                  NaN   
75%                   2004.000000         NaN                  NaN   
max                   2009.000000         NaN                  NaN   

              Outlet_Type  Item_Outlet_Sales  
count                8523        8523.000000  
unique                  4                NaN  
top     Supermarket Type1                NaN  
freq                 5577                NaN  
mean                  NaN        2181.288914  
std                   NaN        1706.499616  
min                   NaN          33.290000  
25%                   NaN         834.247400  
50%                   NaN        1794.331000  
75%                   NaN        3101.296400  
max                   NaN       13086.964800

In [5]:
train.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [6]:
train.Outlet_Size.value_counts()

Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

In [7]:
train = train.fillna({"Item_Weight": "12.85"})
train = train.fillna({"Outlet_Size": "Medium"})

In [8]:
train.shape

(8523, 12)

In [9]:
X = train.iloc[:,0:-1].values
y = train.iloc[:,-1].values

In [10]:
X.shape, y.shape

((8523, 11), (8523,))

In [11]:
train.describe(include="O")

Item_Identifier Item_Weight Item_Fat_Content              Item_Type  \
count             8523        8523             8523                   8523   
unique            1559         416                5                     16   
top              FDW13       12.85          Low Fat  Fruits and Vegetables   
freq                10        1463             5089                   1232   

       Outlet_Identifier Outlet_Size Outlet_Location_Type        Outlet_Type  
count               8523        8523                 8523               8523  
unique                10           3                    3                  4  
top               OUT027      Medium               Tier 3  Supermarket Type1  
freq                 935        5203                 3350               5577

In [12]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
labelencoder_X_3 = LabelEncoder()
X[:,4] = labelencoder_X_3.fit_transform(X[:,4])
labelencoder_X_4 = LabelEncoder()
X[:,6] = labelencoder_X_4.fit_transform(X[:,6])
labelencoder_X_5 = LabelEncoder()
X[:,8] = labelencoder_X_5.fit_transform(X[:,8])
labelencoder_X_6 = LabelEncoder()
X[:,9] = labelencoder_X_6.fit_transform(X[:,9])
labelencoder_X_7 = LabelEncoder()
X[:,10] = labelencoder_X_7.fit_transform(X[:,10])

In [13]:
from sklearn.feature_selection import VarianceThreshold

In [14]:
# Create VarianceThreshold object with a variance with a threshold of 0.5
thresholder = VarianceThreshold(threshold =.5)

# Conduct variance thresholding
X_var = thresholder.fit(X)
features = thresholder.get_support(indices = True)  # Returns array of indexes of nonremoved features
X_high_variance = thresholder.transform(X)

In [15]:
np.shape(X_high_variance)

(8523, 8)

In [16]:
features

array([ 0,  1,  4,  5,  6,  7,  9, 10], dtype=int64)

In [17]:
columns = train.columns

In [18]:
new_columns = []
for i in range(len(features)):
    name = columns[features[i]]
    new_columns.append(name)

In [19]:
len(new_columns)

8

In [20]:
df = pd.DataFrame(X_high_variance)
df.columns = new_columns

In [21]:
df.head()

Item_Identifier  Item_Weight  Item_Type  Item_MRP  Outlet_Identifier  \
0            156.0         9.30        4.0  249.8092                9.0   
1              8.0         5.92       14.0   48.2692                3.0   
2            662.0        17.50       10.0  141.6180                9.0   
3           1121.0        19.20        6.0  182.0950                0.0   
4           1297.0         8.93        9.0   53.8614                1.0   

   Outlet_Establishment_Year  Outlet_Location_Type  Outlet_Type  
0                     1999.0                   0.0          1.0  
1                     2009.0                   2.0          2.0  
2                     1999.0                   0.0          1.0  
3                     1998.0                   2.0          0.0  
4                     1987.0                   2.0          1.0

In [22]:
X = df.values

In [23]:
y.shape, X.shape

((8523,), (8523, 8))

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X

array([[1.560e+02, 9.300e+00, 4.000e+00, ..., 1.999e+03, 0.000e+00,
        1.000e+00],
       [8.000e+00, 5.920e+00, 1.400e+01, ..., 2.009e+03, 2.000e+00,
        2.000e+00],
       [6.620e+02, 1.750e+01, 1.000e+01, ..., 1.999e+03, 0.000e+00,
        1.000e+00],
       ...,
       [1.357e+03, 1.060e+01, 8.000e+00, ..., 2.004e+03, 1.000e+00,
        1.000e+00],
       [6.810e+02, 7.210e+00, 1.300e+01, ..., 2.009e+03, 2.000e+00,
        2.000e+00],
       [5.000e+01, 1.480e+01, 1.400e+01, ..., 1.997e+03, 0.000e+00,
        1.000e+00]])

In [26]:
y

array([3735.138 ,  443.4228, 2097.27  , ..., 1193.1136, 1845.5976,
        765.67  ])

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [28]:
X_train.shape

(6818, 8)

In [30]:
from sklearn.ensemble import RandomForestRegressor

In [33]:
reg = RandomForestRegressor(n_estimators= 100, random_state = 0)
reg.fit(X_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [34]:
y_pred = reg.predict(X_test)

In [35]:
y_pred

array([2829.124018, 2421.108462, 2243.559576, ..., 2774.568366,
       1978.937366, 1419.838474])

In [36]:
from sklearn.metrics import mean_squared_error

In [37]:
mse = mean_squared_error(y_test, y_pred)

In [38]:
rmse = np.sqrt(mse)

In [39]:
mse, rmse

(1391233.235205274, 1179.5055045252116)

In [40]:
test.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility    Item_Type  \
0           FDW58       20.750          Low Fat         0.007565  Snack Foods   
1           FDW14        8.300              reg         0.038428        Dairy   
2           NCN55       14.600          Low Fat         0.099575       Others   
3           FDQ58        7.315          Low Fat         0.015388  Snack Foods   
4           FDY38          NaN          Regular         0.118599        Dairy   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year Outlet_Size  \
0  107.8622            OUT049                       1999      Medium   
1   87.3198            OUT017                       2007         NaN   
2  241.7538            OUT010                       1998         NaN   
3  155.0340            OUT017                       2007         NaN   
4  234.2300            OUT027                       1985      Medium   

  Outlet_Location_Type        Outlet_Type  
0               Tier 1  Supermarket Type1  
1               Tier 2  Supermarket Type1  
2               Tier 3      Grocery Store  
3               Tier 2  Supermarket Type1  
4               Tier 3  Supermarket Type3

In [41]:
columns = test.columns

In [42]:
drop_columns = []
for i in range(len(columns)):
    if columns[i] not in new_columns:
        drop_columns.append(columns[i])

In [43]:
len(drop_columns)

3

In [44]:
test = test.drop(labels=drop_columns,axis=1)

In [45]:
test.head()

Item_Identifier  Item_Weight    Item_Type  Item_MRP Outlet_Identifier  \
0           FDW58       20.750  Snack Foods  107.8622            OUT049   
1           FDW14        8.300        Dairy   87.3198            OUT017   
2           NCN55       14.600       Others  241.7538            OUT010   
3           FDQ58        7.315  Snack Foods  155.0340            OUT017   
4           FDY38          NaN        Dairy  234.2300            OUT027   

   Outlet_Establishment_Year Outlet_Location_Type        Outlet_Type  
0                       1999               Tier 1  Supermarket Type1  
1                       2007               Tier 2  Supermarket Type1  
2                       1998               Tier 3      Grocery Store  
3                       2007               Tier 2  Supermarket Type1  
4                       1985               Tier 3  Supermarket Type3

In [46]:
test.isna().sum()

Item_Identifier                0
Item_Weight                  976
Item_Type                      0
Item_MRP                       0
Outlet_Identifier              0
Outlet_Establishment_Year      0
Outlet_Location_Type           0
Outlet_Type                    0
dtype: int64

In [47]:
test.describe(include="all")

Item_Identifier  Item_Weight    Item_Type     Item_MRP  \
count             5681  4705.000000         5681  5681.000000   
unique            1543          NaN           16          NaN   
top              FDN52          NaN  Snack Foods          NaN   
freq                 8          NaN          789          NaN   
mean               NaN    12.695633          NaN   141.023273   
std                NaN     4.664849          NaN    61.809091   
min                NaN     4.555000          NaN    31.990000   
25%                NaN     8.645000          NaN    94.412000   
50%                NaN    12.500000          NaN   141.415400   
75%                NaN    16.700000          NaN   186.026600   
max                NaN    21.350000          NaN   266.588400   

       Outlet_Identifier  Outlet_Establishment_Year Outlet_Location_Type  \
count               5681                5681.000000                 5681   
unique                10                        NaN                    3   
top               OUT027                        NaN               Tier 3   
freq                 624                        NaN                 2233   
mean                 NaN                1997.828903                  NaN   
std                  NaN                   8.372256                  NaN   
min                  NaN                1985.000000                  NaN   
25%                  NaN                1987.000000                  NaN   
50%                  NaN                1999.000000                  NaN   
75%                  NaN                2004.000000                  NaN   
max                  NaN                2009.000000                  NaN   

              Outlet_Type  
count                5681  
unique                  4  
top     Supermarket Type1  
freq                 3717  
mean                  NaN  
std                   NaN  
min                   NaN  
25%                   NaN  
50%                   NaN  
75%                   NaN  
max                   NaN

In [48]:
test = test.fillna({"Item_Weight": "12.69"})

In [49]:
X2 = test.iloc[:,:].values

In [50]:
test.describe(include="O")

Item_Identifier Item_Weight    Item_Type Outlet_Identifier  \
count             5681        5681         5681              5681   
unique            1543         411           16                10   
top              FDN52       12.69  Snack Foods            OUT027   
freq                 8         976          789               624   

       Outlet_Location_Type        Outlet_Type  
count                  5681               5681  
unique                    3                  4  
top                  Tier 3  Supermarket Type1  
freq                   2233               3717

In [51]:
X2[0]

array(['FDW58', 20.75, 'Snack Foods', 107.8622, 'OUT049', 1999, 'Tier 1',
       'Supermarket Type1'], dtype=object)

In [52]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X2[:,0] = labelencoder_X.fit_transform(X2[:,0])
labelencoder_X_2 = LabelEncoder()
X2[:,2] = labelencoder_X_2.fit_transform(X2[:,2])
labelencoder_X_3 = LabelEncoder()
X2[:,4] = labelencoder_X_3.fit_transform(X2[:,4])
labelencoder_X_4 = LabelEncoder()
X2[:,6] = labelencoder_X_4.fit_transform(X2[:,6])
labelencoder_X_5 = LabelEncoder()
X2[:,7] = labelencoder_X_5.fit_transform(X2[:,7])


In [53]:
X2.shape

(5681, 8)

In [54]:
y_pred2 = reg.predict(X2)

In [55]:
y_pred2

array([1709.90756 , 1368.039234,  559.764692, ..., 1883.288538,
       3970.89778 , 1546.939694])

In [56]:
submit = pd.DataFrame()
submit['Item_Identifier'] = test['Item_Identifier'].values
submit['Outlet_Identifier'] = test['Outlet_Identifier'].values
submit['Item_Outlet_Sales'] = y_pred2

In [71]:
submit.head()

Item_Identifier Outlet_Identifier  Item_Outlet_Sales
0           FDW58            OUT049        1823.183313
1           FDW14            OUT017         980.127755
2           NCN55            OUT010        2339.841455
3           FDQ58            OUT017        2036.126694
4           FDY38            OUT027        5235.655268

In [72]:
submit_file = submit.to_csv('submission.csv', index = False)