In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv")

In [3]:
train_data.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [4]:
train_data.shape

(54808, 14)

In [5]:
train_data.isna().sum()

employee_id                0
department                 0
region                     0
education               2409
gender                     0
recruitment_channel        0
no_of_trainings            0
age                        0
previous_year_rating    4124
length_of_service          0
KPIs_met >80%              0
awards_won?                0
avg_training_score         0
is_promoted                0
dtype: int64

In [6]:
train_data.describe(include="all")

employee_id         department    region   education gender  \
count   54808.000000              54808     54808       52399  54808   
unique           NaN                  9        34           3      2   
top              NaN  Sales & Marketing  region_2  Bachelor's      m   
freq             NaN              16840     12343       36669  38496   
mean    39195.830627                NaN       NaN         NaN    NaN   
std     22586.581449                NaN       NaN         NaN    NaN   
min         1.000000                NaN       NaN         NaN    NaN   
25%     19669.750000                NaN       NaN         NaN    NaN   
50%     39225.500000                NaN       NaN         NaN    NaN   
75%     58730.500000                NaN       NaN         NaN    NaN   
max     78298.000000                NaN       NaN         NaN    NaN   

       recruitment_channel  no_of_trainings           age  \
count                54808     54808.000000  54808.000000   
unique                   3              NaN           NaN   
top                  other              NaN           NaN   
freq                 30446              NaN           NaN   
mean                   NaN         1.253011     34.803915   
std                    NaN         0.609264      7.660169   
min                    NaN         1.000000     20.000000   
25%                    NaN         1.000000     29.000000   
50%                    NaN         1.000000     33.000000   
75%                    NaN         1.000000     39.000000   
max                    NaN        10.000000     60.000000   

        previous_year_rating  length_of_service  KPIs_met >80%   awards_won?  \
count           50684.000000       54808.000000   54808.000000  54808.000000   
unique                   NaN                NaN            NaN           NaN   
top                      NaN                NaN            NaN           NaN   
freq                     NaN                NaN            NaN           NaN   
mean                3.329256           5.865512       0.351974      0.023172   
std                 1.259993           4.265094       0.477590      0.150450   
min                 1.000000           1.000000       0.000000      0.000000   
25%                 3.000000           3.000000       0.000000      0.000000   
50%                 3.000000           5.000000       0.000000      0.000000   
75%                 4.000000           7.000000       1.000000      0.000000   
max                 5.000000          37.000000       1.000000      1.000000   

        avg_training_score   is_promoted  
count         54808.000000  54808.000000  
unique                 NaN           NaN  
top                    NaN           NaN  
freq                   NaN           NaN  
mean             63.386750      0.085170  
std              13.371559      0.279137  
min              39.000000      0.000000  
25%              51.000000      0.000000  
50%              60.000000      0.000000  
75%              76.000000      0.000000  
max              99.000000      1.000000

In [7]:
train_data.describe(include="O")

department    region   education gender recruitment_channel
count               54808     54808       52399  54808               54808
unique                  9        34           3      2                   3
top     Sales & Marketing  region_2  Bachelor's      m               other
freq                16840     12343       36669  38496               30446

In [8]:
train_data = train_data.fillna({"education": "Bachelor's"})
train_data = train_data.fillna({"previous_year_rating": round(np.mean(train_data['previous_year_rating']))})

In [9]:
train_data.shape

(54808, 14)

In [10]:
train_data.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [11]:
train_data_T = train_data.T
train_data_T.shape

(14, 54808)

In [12]:
train_data_T.duplicated().sum()

0

In [13]:
columns = train_data.columns

In [14]:
columns.shape

(14,)

In [15]:
X = train_data.iloc[:,0:-1].values
y = train_data.iloc[:,-1].values

In [16]:
X.shape, y.shape

((54808, 13), (54808,))

In [17]:
for i in range(13):
    print(i,X[0][i])

0 65438
1 Sales & Marketing
2 region_7
3 Master's & above
4 f
5 sourcing
6 1
7 35
8 5.0
9 8
10 1
11 0
12 49


In [18]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
labelencoder_X_3 = LabelEncoder()
X[:,3] = labelencoder_X_3.fit_transform(X[:,3])
labelencoder_X_4 = LabelEncoder()
X[:,4] = labelencoder_X_4.fit_transform(X[:,4])
labelencoder_X_5 = LabelEncoder()
X[:,5] = labelencoder_X_5.fit_transform(X[:,5])

In [19]:
from sklearn.feature_selection import VarianceThreshold

In [20]:
# Create VarianceThreshold object with a variance with a threshold of 0.5
thresholder = VarianceThreshold(threshold =.5)

# Conduct variance thresholding
X_var = thresholder.fit(X)
features = thresholder.get_support(indices = True)  # Returns array of indexes of nonremoved features
X_high_variance = thresholder.transform(X)

In [21]:
np.shape(X_high_variance)

(54808, 9)

In [22]:
features

array([ 0,  1,  2,  3,  5,  7,  8,  9, 12], dtype=int64)

In [23]:
new_columns = []
for i in range(len(features)):
    name = columns[features[i]]
    new_columns.append(name)

In [24]:
new_columns

['employee_id',
 'department',
 'region',
 'education',
 'recruitment_channel',
 'age',
 'previous_year_rating',
 'length_of_service',
 'avg_training_score']

In [25]:
len(new_columns)

9

In [26]:
df = pd.DataFrame(X_high_variance)
df.columns = new_columns

In [27]:
df.head()

employee_id department region education recruitment_channel age  \
0       65438          7     31         2                   2  35   
1       65141          4     14         0                   0  30   
2        7513          7     10         0                   2  34   
3        2542          7     15         0                   0  39   
4       48945          8     18         0                   0  45   

  previous_year_rating length_of_service avg_training_score  
0                    5                 8                 49  
1                    5                 4                 60  
2                    3                 7                 50  
3                    1                10                 50  
4                    3                 2                 73

In [28]:
X = df.values

In [29]:
y.shape, X.shape

((54808,), (54808, 9))

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X

array([[65438, 7, 31, ..., 5.0, 8, 49],
       [65141, 4, 14, ..., 5.0, 4, 60],
       [7513, 7, 10, ..., 3.0, 7, 50],
       ...,
       [13918, 0, 0, ..., 5.0, 3, 79],
       [13614, 7, 33, ..., 1.0, 2, 45],
       [51526, 2, 14, ..., 1.0, 5, 49]], dtype=object)

In [32]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [34]:
X_train.shape

(43846, 9)

## Random Forest

In [35]:
from sklearn.ensemble import RandomForestRegressor

In [36]:
reg = RandomForestRegressor(n_estimators=1000,random_state=0)
reg.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [37]:
y_pred = reg.predict(X_test)

In [38]:
y_pred

array([0.071, 0.069, 0.017, ..., 0.029, 0.075, 0.039])

In [39]:
for i in range(len(y_pred)):
    y_pred[i] = round(y_pred[i])

In [40]:
y_pred.astype(int)

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
reg.score(X_test,y_pred)

0.5707711254364665

In [42]:
from sklearn.metrics import mean_squared_error

In [43]:
mse = mean_squared_error(y_test, y_pred)

In [44]:
rmse = np.sqrt(mse)

In [45]:
mse, rmse

(0.06148513045064769, 0.24796195363532628)

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred.astype(int))

In [47]:
cm

array([[9999,   36],
       [ 638,  289]], dtype=int64)

## Logistic Regression

In [48]:
from sklearn.linear_model import LogisticRegression
reg2 = LogisticRegression(random_state=0)
reg2.fit(X_train,y_train)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [49]:
y_pred2 = reg2.predict(X_test)

In [50]:
y_pred2

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
cm2 = confusion_matrix(y_test,y_pred2)
cm2

array([[10035,     0],
       [  927,     0]], dtype=int64)

In [52]:
reg2.score(X_test,y_pred2)

1.0

## Gaussian Naive Bayes

In [53]:
from sklearn.naive_bayes import GaussianNB
reg3 = GaussianNB()
reg3.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [54]:
y_pred3 = reg3.predict(X_test)

In [55]:
y_pred3

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [56]:
cm3 = confusion_matrix(y_test,y_pred3)
cm3

array([[10035,     0],
       [  914,    13]], dtype=int64)

In [57]:
reg3.score(X_test,y_pred3)

1.0

## Decision Tree

In [58]:
from sklearn.tree import DecisionTreeClassifier
reg4 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
reg4.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [59]:
y_pred4 = reg4.predict(X_test)

In [60]:
y_pred4

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [61]:
cm4 = confusion_matrix(y_test,y_pred4)
cm4

array([[9373,  662],
       [ 581,  346]], dtype=int64)

In [62]:
reg4.score(X_test,y_pred4)

1.0

## Test data

In [63]:
test_data.head()

employee_id         department     region   education gender  \
0         8724         Technology  region_26  Bachelor's      m   
1        74430                 HR   region_4  Bachelor's      f   
2        72255  Sales & Marketing  region_13  Bachelor's      m   
3        38562        Procurement   region_2  Bachelor's      f   
4        64486            Finance  region_29  Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   24                   NaN   
1               other                1   31                   3.0   
2               other                1   31                   1.0   
3               other                3   31                   2.0   
4            sourcing                1   30                   4.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  
0                  1              1            0                  77  
1                  5              0            0                  51  
2                  4              0            0                  47  
3                  9              0            0                  65  
4                  7              0            0                  61

In [64]:
columns = test_data.columns

In [65]:
drop_columns = []
for i in range(len(columns)):
    if columns[i] not in new_columns:
        drop_columns.append(columns[i])

In [66]:
len(drop_columns)

4

In [67]:
test_data = test_data.drop(labels=drop_columns,axis=1)

In [68]:
test_data.head()

employee_id         department     region   education recruitment_channel  \
0         8724         Technology  region_26  Bachelor's            sourcing   
1        74430                 HR   region_4  Bachelor's               other   
2        72255  Sales & Marketing  region_13  Bachelor's               other   
3        38562        Procurement   region_2  Bachelor's               other   
4        64486            Finance  region_29  Bachelor's            sourcing   

   age  previous_year_rating  length_of_service  avg_training_score  
0   24                   NaN                  1                  77  
1   31                   3.0                  5                  51  
2   31                   1.0                  4                  47  
3   31                   2.0                  9                  65  
4   30                   4.0                  7                  61

In [69]:
test_data.isna().sum()

employee_id                0
department                 0
region                     0
education               1034
recruitment_channel        0
age                        0
previous_year_rating    1812
length_of_service          0
avg_training_score         0
dtype: int64

In [70]:
test_data.describe(include="O")

department    region   education recruitment_channel
count               23490     23490       22456               23490
unique                  9        34           3                   3
top     Sales & Marketing  region_2  Bachelor's               other
freq                 7315      5299       15578               13078

In [71]:
test_data = test_data.fillna({"education": "Bachelor's"})
test_data = test_data.fillna({"previous_year_rating": round(np.mean(test_data['previous_year_rating']))})

In [72]:
test_data.isna().sum()

employee_id             0
department              0
region                  0
education               0
recruitment_channel     0
age                     0
previous_year_rating    0
length_of_service       0
avg_training_score      0
dtype: int64

In [73]:
X2 = test_data.iloc[:,:].values

In [74]:
X2.shape

(23490, 9)

In [75]:
for i in range(9):
    print(i,X2[0][i])

0 8724
1 Technology
2 region_26
3 Bachelor's
4 sourcing
5 24
6 3.0
7 1
8 77


In [76]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X2[:,1] = labelencoder_X.fit_transform(X2[:,1])
labelencoder_X_2 = LabelEncoder()
X2[:,2] = labelencoder_X_2.fit_transform(X2[:,2])
labelencoder_X_3 = LabelEncoder()
X2[:,3] = labelencoder_X_3.fit_transform(X2[:,3])
labelencoder_X_4 = LabelEncoder()
X2[:,4] = labelencoder_X_4.fit_transform(X2[:,4])

In [77]:
X2.shape

(23490, 9)

In [78]:
y_prediction = reg.predict(X2)

In [79]:
y_prediction.shape

(23490,)

In [81]:
for i in range(len(y_prediction)):
    y_prediction[i] = round(y_prediction[i])

In [82]:
y_prediction

array([0., 0., 0., ..., 0., 0., 1.])

In [83]:
submit = pd.DataFrame()
submit['employee_id'] = test_data['employee_id'].values
submit['is_promoted'] = y_prediction.astype(int)

In [84]:
submit.head()

employee_id  is_promoted
0         8724            0
1        74430            0
2        72255            0
3        38562            0
4        64486            0

In [85]:
submit.shape

(23490, 2)

In [86]:
submit_file = submit.to_csv('submission2.csv', index = False)

In [87]:
a = []
for i in range(len(submit['is_promoted'])):
    if submit['is_promoted'][i]==1:
#         print(submit['employee_id'][i])
        a.append(submit['employee_id'][i])

In [88]:
len(a)

384